name: Run tests

on:
  workflow_call:
    secrets:
      PAT:
        required: true

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Cache vendor
        uses: actions/cache@v3
        with:
          key: ${{ hashFiles('./src/composer.lock') }}
          path: |
            ./src/vendor

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('./src/composer.lock') }}

      - name: Composer install
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.PAT }}"} }'
        uses: php-actions/composer@v6
        with:
          args: -d ./src
          php_version: "8.1"
          php_extensions: sockets pcntl redis gd
          version: 2.x

      - name: Bolide setup up
        run: cd src && cp .env.example .env && docker network create bolide && docker-compose run composer chmod -R 777 storage && docker-compose run composer chmod -R 777 bootstrap/cache && docker-compose run composer i --ignore-platform-reqs && docker-compose run artisan migrate --seed && docker-compose run artisan storage:link

      - name: Execute tests via artisan
        run: cd src && docker-compose run artisan test
